apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  default_server;
        location / {
          add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
          expires off;
          default_type application/json;
          return 200 '{"pod":"${HOSTNAME}","user":"${SECRET_USERNAME}","password":"${SECRET_PASSWORD}"}';
      }
    }