apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            expires off;
            default_type application/json;
            return 200 "{\"name\":\"$HOSTNAME\",\"user\":\"${SECRET_USERNAME}\",\"password\":\"${SECRET_PASSWORD}\"}";
        }
      }
    }