resources:
- ingress.yaml
- service.yaml
- deployment.yaml

labels: 
  app: kustomapp

commonAnnotations: 
  app: kustomapp-annotation

nameSuffix: "-001"

configMapGenerator:
- name: nginx-template-configmap
  files:
  - nginx-template.conf