resources:
- service.yaml
- deployment.yaml

commonLabels: 
  app: kustomapp

commonAnnotations: 
  app: kustomapp-annotation

## probleme avec ingress
#nameSuffix: "-001"

configMapGenerator:
- name: nginx-template-configmap
  files:
  - nginx-template.conf