resources:
- service.yaml
- deployment.yaml
- ingress.yaml

commonLabels: 
  app: kustomapp

commonAnnotations: 
  app: kustomapp-annotation

nameSuffix: "-v1.0"

configMapGenerator:
- name: nginx-template-configmap
  files:
  - nginx-template.conf