resources:
- service.yaml
- deployment.yaml
- ingress.yaml

commonLabels: 
  app: kustomapp

commonAnnotations: 
  app: kustomapp-annotation

# https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
# Don't use "." char in name to avoid issue
nameSuffix: "-v1-0"

configMapGenerator:
- name: nginx-template-configmap
  files:
  - nginx-template.conf