resources:
- ../../base

namespace: dev

## probleme avec ingress
#namePrefix: dev-
patches:
- path: increase_replicas.yaml
- path: ingress.yaml

secretGenerator:
- name: credential-secret
  literals:
  - username=devadmin
  - password=hello