resources:
- ../../base

namespace: dev

#namePrefix: dev-

patches:
- path: replicas.yaml
- path: ingress.yaml

secretGenerator:
- name: credential-secret
  literals:
  - username=devadmin
  - password=hello