apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kustomapp
spec:
  tls:
  - hosts:
    - kustomapp.prod.95-181-220-26.nip.io
    secretName: kustomapp.prod.95-181-220-26.nip.io-tls
  rules:
  - host: kustomapp.prod.95-181-220-26.nip.io
