resources:
- ../../base

namespace: prod


#namePrefix: prod-

patches:
- path: replicas.yaml
- path: ingress.yaml

secretGenerator:
- name: credential-secret
  literals:
  - username=admin
  - password=secret